PNI_lea-meter_Projekt/MentorskiApp/MentorskiApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mentorski.urls')),
]

PNI_lea-meter_Projekt/MentorskiApp/mentorski/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.registerPage, name='register'),
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutUser, name='logout'),
    path('upisni_list/<str:sk>/', views.upisniList, name='upisni_list'),
    path('upis/<str:pk>/<str:sk>/', views.upis, name='upis'),
    path('upis_izbrisi/<str:pk>/<str:sk>/', views.izbrisiUpis, name='upis_izbrisi'),
    path('upis_status/<str:pk>/<str:sk>/', views.statusUpis, name='upis_status'),
    path('predmeti', views.predmeti, name='predmeti'),
    path('predmet_uredi/<str:pk>/', views.predmetUredi, name='predmet_uredi'),
    path('predmet_novi', views.predmetDodaj, name='predmet_novi'),
    path('studenti', views.studenti, name='studenti'),
]

PNI_lea-meter_Projekt/MentorskiApp/mentorski/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser

class Korisnici(AbstractUser):
    
    email = models.EmailField(verbose_name="email", max_length=64, unique=True )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','password']

    MENTOR = 'mentor'
    STUDENT = 'student'
    ROLES = (
        (MENTOR, _('mentor')),
        (STUDENT, _('student')),
    )
    role = models.CharField(_('role'), default=STUDENT, choices=ROLES, max_length=20)

    NONE = 'none'
    REDOVNI = 'redovni'
    IZVANREDNI='izvanredni'
    STATUSES=(
        (NONE, _('none')),
        (REDOVNI, _('redovni')),
        (IZVANREDNI, _('izvanredni')),
    )
    status = models.CharField(_('status'), default=NONE, choices=STATUSES, max_length=20)
    
    def __str__(self):
        return self.email



class Predmeti(models.Model):
    ime = models.CharField(max_length=255, unique=True)
    kod = models.CharField(max_length=16, primary_key=True, unique=True )
    program = models.CharField(max_length=225)
    ECTS = models.IntegerField()
    sem_redovni = models.IntegerField()
    sem_izvanredni = models.IntegerField()
    
    DA = 'da'
    NE = 'ne'
    IZBORNI=(
        (DA, _('da')),
        (NE, _('ne')),
    )
    izborni = models.CharField(_('izborni'), default=NE, choices=IZBORNI, max_length=10)

    def __str__(self):
        return self.ime

class Upisi(models.Model):
    student = models.ForeignKey(Korisnici, on_delete=models.CASCADE)
    predmet = models.ForeignKey(Predmeti, on_delete=models.CASCADE)

    POLOŽENO = 'položeno'
    NEPOLOŽENO = 'nepoloženo'
    IZBOR=(
        (POLOŽENO, _('položeno')),
        (NEPOLOŽENO, _('nepoloženo')),
    )

    status = models.CharField(_('status'), default=NEPOLOŽENO, choices=IZBOR, max_length=20)
    class Meta:
        unique_together = [['student','predmet']]

PNI_lea-meter_Projekt/MentorskiApp/mentorski/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Korisnici, Upisi, Predmeti

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = Korisnici
        fields = ('email', 'password', 'role','status')

class CreateUserForm(UserCreationForm):
	class Meta:
		model = Korisnici
		fields = ['username', 'email', 'password1', 'password2', 'status']

class UpisForm(ModelForm):
    class Meta:
        model = Upisi
        fields = ['predmet','student']
        widgets = {'predmet': forms.HiddenInput(),'student': forms.HiddenInput()}

class PredmetForm(ModelForm):
    class Meta:
        model = Predmeti
        fields = '__all__'

PNI_lea-meter_Projekt/MentorskiApp/mentorski/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *
from .decorators import *

@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        status = form.data.get('status')
            
        if form.is_valid() and status != "none":
            form.save()
            email = form.cleaned_data.get('email')
            messages.success(request, 'Account was created for ' + email)

            return redirect('login')
    context = {'form':form}
    return render(request, 'register.html', context)


@unauthenticated_user
def loginPage(request):
	if request.method == 'POST':
		email = request.POST.get('email')
		password =request.POST.get('password')
		user = authenticate(request, email=email, password=password)
		if user is not None:
			login(request, user)
			if request.user.role=="student":
				return redirect('upisni_list', user.id)
			if request.user.role=="mentor":
				return redirect('predmeti')
		else:
			messages.info(request, 'Email OR password is incorrect')
	context = {}
	return render(request, 'login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('login')


@allowed_users(allowed_roles=["student","mentor"])
def upisniList(request, sk):
	user = request.user
	if user.role == "mentor":
		user = Korisnici.objects.get(id=sk)
	
	upisani_predmeti = user.upisi_set.all()
	u = upisani_predmeti.values('predmet')
	neupisani_predmeti = Predmeti.objects.exclude(upisi__predmet__in=u).distinct()
	predmeti = Predmeti.objects.filter(upisi__predmet__in=u).distinct()
	
	if(user.status == "izvanredni"):
		predmeti = predmeti.order_by('sem_izvanredni')
	if(user.status == "redovni"):
		predmeti = predmeti.order_by('sem_redovni')

	context = {'neupisani_predmeti':neupisani_predmeti, 'upisani_predmeti':upisani_predmeti,'predmeti':predmeti, 'student':user}
	return render(request, 'upisni_list.html', context)


@allowed_users(allowed_roles=["student","mentor"])
def upis(request,pk,sk):
	form = UpisForm(initial={'predmet':pk,'student':sk})
	predmet = Predmeti.objects.get(kod=pk)
	if request.method == 'POST':
		form = UpisForm(request.POST,initial={'predmet':pk,'student':sk})
		if form.is_valid():
			form.save()
			return redirect('upisni_list', sk)
	context = {'form':form, 'predmet':predmet, 'student_id':sk}
	return render(request, 'upis.html', context)


@allowed_users(allowed_roles=["student","mentor"])
def izbrisiUpis(request,pk,sk):
	upis = Upisi.objects.get(predmet_id=pk, student_id=sk)
	predmet = Predmeti.objects.get(kod=pk)
	student = Korisnici.objects.get(id=sk)
	if request.method == "POST":
		upis.delete()
		return redirect('upisni_list', student.id)
	context = {'predmet':predmet, 'student':student}
	return render(request, 'upis_izbrisi.html', context)


@allowed_users(allowed_roles=["student","mentor"])
def statusUpis(request,pk,sk):
	predmet = Predmeti.objects.get(kod=pk)
	student = Korisnici.objects.get(id=sk)
	upis = Upisi.objects.get(predmet_id=pk, student_id=sk)
	
	print(upis.status)
	if request.method == "POST":
		
		if upis.status == "položeno":
			upis.status = "nepoloženo"
			upis.save()
		elif upis.status == "nepoloženo":
			upis.status = "položeno"
			upis.save()
		print(upis.status)
		return redirect('upisni_list', student.id)
	context = {'predmet':predmet, 'student':student,'upis':upis}
	return render(request, 'upis_status.html', context)


@allowed_users(allowed_roles=["mentor"])
def predmeti(request):
	predmeti = Predmeti.objects.all()
	context = {'predmeti':predmeti}
	return render(request, 'predmeti.html', context)


@allowed_users(allowed_roles=["mentor"])
def predmetUredi(request,pk):
	predmet = Predmeti.objects.get(kod=pk)

	form = PredmetForm(instance=predmet)
	if request.method == 'POST':
		form = PredmetForm(request.POST, instance=predmet)
		if form.is_valid():
			form.save()
			return redirect('predmeti')

	context = {'form':form}
	return render(request, 'predmet_uredi.html', context)


@allowed_users(allowed_roles=["mentor"])
def predmetDodaj(request):
	form = PredmetForm()
	if request.method == 'POST':
		form = PredmetForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('predmeti')

	context = {'form':form}
	return render(request, 'predmet_uredi.html', context)


@allowed_users(allowed_roles=["mentor"])
def studenti(request):
	studenti= Korisnici.objects.filter(role="student")

	context = {'studenti':studenti}
	return render(request, 'studenti.html', context)

PNI_lea-meter_Projekt/MentorskiApp/templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background:#d9ecec;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background:#9838e7d8;
			color: white;
		}
		.login_btn:focus {
			box-shadow: none;
			outline: 0px;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #9838e7d8;
			color: white;
			border: 0;
			border-radius: 0.25rem 0 0 0.25rem;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none;
			outline: 0px;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="email" placeholder="Email..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Unesite lozinku..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Nemate račun? <a href="{% url 'register' %}" class="ml-2">Registriraj me</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

PNI_lea-meter_Projekt/MentorskiApp/templates/main.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">

    </head>
    <body>
        {% if request.user.role == "student" %}
        {% include 'navbar.html' %}
        {% endif %}
        {% if request.user.role == "mentor" %}
        {% include 'navbar_mentor.html' %}
        {% endif %}
        <div class="container-fluid">
        {% block content %}

        {% endblock %}
        </div>
        
    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

PNI_lea-meter_Projekt/MentorskiApp/templates/navbar.html
{% load static %}

<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>

      </ul>
    </div>
    <span class="hello-msg">Hello, {{request.user.username}}</span>
</nav>

PNI_lea-meter_Projekt/MentorskiApp/templates/navbar_mentor.html
{% load static %}
<style>
    .hello-msg{
      font-size: 18px;
      color: #fff;
      margin-right: 20px;
    }
</style>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'predmeti' %}">Predmeti</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'studenti' %}">Studenti</a>
            </li>        
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
  
        </ul>
      </div>
      <span class="hello-msg">Hello, {{request.user.username}}</span>
  </nav>

PNI_lea-meter_Projekt/MentorskiApp/templates/predmet_uredi.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}


<div class="row">
	<div class="col-md-5">
		<div class="card card-body">
            <h5>UREDI PREDMET</h5>
			<form action="" method="POST">
				{% csrf_token %}
                <table class="table table-sm">
                    <tr>
                        <th>Kod (zabranjeno mijenjane)</th>
                        <td>{{form.kod}}</td>
                    </tr>
                    <tr>
                        <th>Ime Predmeta</th>
                        <td>{{form.ime}}</td>
                    </tr>
                    <tr>
                        <th>Program</th>
                        <td>{{form.program}}</td>
                    </tr>
                    <tr>
                        <th>ECTS</th>
                        <td>{{form.ECTS}}</td>
                    </tr>
                    <tr>
                        <th>Semestar Redovni</th>
                        <td>{{form.sem_redovni}}</td>
                    </tr>
                    <tr>
                        <th>Semestar Izvanredni</th>
                        <td>{{form.sem_izvanredni}}</td>
                    </tr>
                    <tr>
                        <th>Izborni</th>
                        <td>{{form.izborni}}</td>
                    </tr>
                </table>

                <a class="btn btn-warning" href="{% url 'predmeti' %}" name="Odustani">Odustani</a>
                <button class="btn btn-danger" type="submit" name="Spremi">Spremi</button>

			</form>

		</div>
	</div>
</div>


{% endblock %}

PNI_lea-meter_Projekt/MentorskiApp/templates/predmeti.html
{%  extends 'main.html' %}

{% block content %}
<br>

<div class="row">
	<div class="col-md">
		<h5>PREDMETI</h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-info" href="{%  url 'predmet_novi'%}" >Dodaj Novi Predmet</a>
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Kod</th>
                    <th>Ime Predmeta</th>
                    <th>Program</th>
                    <th>ECTS</th>
                    <th>Semestar Redovni</th>
                    <th>Semestar Izvanredni</th>
                    <th>Izborni</th>
				</tr>

				{% for predmet in predmeti %}
					<tr>
						<td><a class="btn btn-info" href="{%  url 'predmet_uredi' predmet.kod %}" >
                            <i class="far fa-edit"></i>
                            </a>
                        </td>
						<td>{{predmet.kod}}</td>
                        <td>{{predmet.ime}}</td>
                        <td>{{predmet.program}}</td>
                        <td>{{predmet.ECTS}}</td>
                        <td>{{predmet.sem_redovni}}</td>
                        <td>{{predmet.sem_izvanredni}}</td>
                        <td>{{predmet.izborni}}</td>

					</tr>
				{% endfor %}

			</table>
		</div>
	</div>
</div>

{% endblock content %}

PNI_lea-meter_Projekt/MentorskiApp/templates/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #d9ecec;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #88afe9;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background:#9838e7d8;
			color: white;
		}
		.login_btn:focus {
			box-shadow: none;
			outline: 0px;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #9838e7d8;
			color: white;
			border: 0;
			border-radius: 0.25rem 0 0 0.25rem;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none;
			outline: 0px;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTRACIJA STUDENTA</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
                        </div>
                        <div class="input-group mb-2">
							<div class="input-group-append">
                                <span class="input-group-text"><i class="fa fa-graduation-cap"></i></span>
                            </div>
                                <select class="custom-select" name="status" id="id_status">
                                    {% for status in form.status %}
                                        {{status}}
                                    {% endfor %}
                                </select>
						</div>



				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Registrirajte se">
				   		</div>

					</form>
				</div>

				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						 <a href="{% url 'login' %}" class="ml-2">Prijavite se!</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Korisničko ime...';
		form_fields[2].placeholder='Email...';
		form_fields[3].placeholder='Unesite lozinku...';
        form_fields[4].placeholder='Ponovno unesite lozinku...';

		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

PNI_lea-meter_Projekt/MentorskiApp/templates/studenti.html
{%  extends 'main.html' %}

{% block content %}
<br>

<div class="row">
	<div class="col-md">
		<h5>STUDENTI</h5>
		<hr>
		<div class="card card-body">
			
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Korisničko Ime</th>
                    <th>Email</th>
                    <th>Status</th>
				</tr>

				{% for student in studenti %}
					<tr>
						<td><a class="btn btn-info" href="{%  url 'upisni_list' student.id %}" >
                            <i class="far fa-edit"></i>
                            </a>
                        </td>
						<td>{{student.username}}</td>
                        <td>{{student.email}}</td>
                        <td>{{student.status}}</td>
					</tr>
				{% endfor %}

			</table>
		</div>
	</div>
</div>

{% endblock content %}

PNI_lea-meter_Projekt/MentorskiApp/templates/upis.html
{%  extends 'main.html' %}

{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">
            <p>Jeste li sigurni da želite upisati predmet "{{predmet.kod}} {{predmet.ime}}"?</p>
            <form action="" method="POST">
                {% csrf_token %}
                {{form}}
                <a class="btn btn-warning" href="{% url 'upisni_list' student_id %}" name="Odustani">Odustani</a>
                <button class="btn btn-info" type="submit" name="Upiši">Upiši</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

PNI_lea-meter_Projekt/MentorskiApp/templates/upis_izbrisi.html
{%  extends 'main.html' %}

{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">
            <p>Jeste li sigurni da želite izbrisati upisani predmet "{{predmet.kod}} {{predmet.ime}}"?</p>
            <form action="{% url 'upis_izbrisi' predmet.kod student.id %}" method="POST">
                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'upisni_list' student.id %}" name="Odustani">Odustani</a>
                <button class="btn btn-danger" type="submit" name="Izbriši">Izbriši</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

PNI_lea-meter_Projekt/MentorskiApp/templates/upis_status.html
{%  extends 'main.html' %}

{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">
            <p>Jeste li sigurni da želite promjeniti status "{{upis.status}}" za predmet "{{predmet.kod}} {{predmet.ime}}"?</p>
            <form action="{% url 'upis_status' predmet.kod student.id %}" method="POST">
                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'upisni_list' student.id %}" name="Odustani">Odustani</a>

                <button class="btn btn-info" type="submit" name="Promijeni">
                    {% if upis.status == "nepoloženo" %}
                        Položeno
                    {% endif %}
                    {% if upis.status == "položeno" %}
                        Nepoloženo
                    {% endif %}
                </button>

            </form>
        </div>
    </div>
</div>

{% endblock content %}